name: Build Sonic Mania 3DS CIA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build 3DS ELF
        run: |
          make PLATFORM=3DS

      - name: Search packaging files
        run: |
          find . -iname "*makerom*"
          find . -iname "*rsf*"
          find . -iname "*cia*"
          find . -iname "*3ds*"