name: Build Sonic Mania 3DS CIA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build 3DS
        run: |
          make PLATFORM=3DS

      - name: Build CIA
        run: |
          cd 3ds
          chmod +x makerom
          chmod +x bannertool
          chmod +x build_cia.sh

          echo "3DS folder:"
          ls -la

          echo "Running CIA script:"
          ./build_cia.sh ../bin/3DS/SonicMania.so

          echo "After build:"
          find . -name "*.bnr"
          find . -name "*.cia"

      - name: Find CIA
        run: |
          echo "Searching entire repo for CIA:"
          find . -name "*.cia"

      - name: Upload CIA
        uses: actions/upload-artifact@v4
        with:
          name: SonicMania-3DS-CIA
          path: "**/*.cia"
          if-no-files-found: warn